{{- if .Values.ingress.enabled }}
apiVersion: {{ include "photoprism.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "nextcloud.fullname" . }}-ingress
  labels:
{{ include "photoprism.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ template "nextcloud.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
              {{- else }}
              serviceName: {{ template "nextcloud.fullname" . }}-service
              servicePort: http
              {{- end }}
        {{- end }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
