name: Lint and Test Charts

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "charts/**/README.md"
      - "LICENSE"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/pull_request_template.md"
      - "CODE_OF_CONDUCT.md"

permissions:
  contents: write

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Check for changes
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if bump is required
        if: steps.list-changed.outputs.changed == 'true'
        id: bumpRequired
        run: |
          # get previous version from chart.yaml on repository default branch
          ## first get the file from main branch using git cli
          git fetch origin ${{ github.event.repository.default_branch }}:${{ github.event.repository.default_branch }}
          ## read the file on the other branch and get the version
          PREVIOUS_VERSION=$(git show ${{ github.event.repository.default_branch }}:charts/photoprism/Chart.yaml | yq eval '.version')
          CURRENT_VERSION=$(yq eval '.version' charts/photoprism/Chart.yaml)

          echo "Previous version: '${PREVIOUS_VERSION}'"
          echo "Current version: '${CURRENT_VERSION}'"

          if [[ "${PREVIOUS_VERSION}" == "${CURRENT_VERSION}" ]]; then
            echo "version not changed yet, bump required"
            echo "required=true" >> "$GITHUB_OUTPUT"
            echo "PREVIOUS_VERSION=${PREVIOUS_VERSION}" >> "$GITHUB_OUTPUT"
            echo "newVersion=$(echo $PREVIOUS_VERSION | awk -F. -v OFS=. '{$NF++;print}')" >> "$GITHUB_OUTPUT"
          fi

      - name: Bump and commit new version
        if: steps.list-changed.outputs.changed == 'true' && steps.bumpRequired.outputs.required == 'true'
        run: |
          yq eval -i '.version = ${{ steps.bumpRequired.outputs.newVersion }}' charts/photoprism/Chart.yaml

          # checkout PR branch
          git checkout ${{ github.event.pull_request.head.ref }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Bump version to '${{ steps.bumpRequired.outputs.newVersion }}'"
          git push origin

          # Continue on the new commit

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
